---
language: python
services: docker

env:
  global:
    - ROLE_NAME: zookeeper
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  - pip install molecule docker ansible

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME alvarobacelar.$ROLE_NAME
  - cd alvarobacelar.$ROLE_NAME
  - ansible-galaxy install -r requirements.yml
  - mv $HOME/.ansible/roles/java $HOME/build/alvarobacelar

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
