---

- name: baixando o zookeper no servidor
  unarchive:
    src: "{{ _zookeeper_link }}"
    dest: "/opt/"
    owner: "{{ user_zoo }}"
    remote_src: true
  become: true

- name: criando um link simbolico no path {{ path_zoo }}
  file:
    src: "/opt/zookeeper-{{ version_zoo }}"
    dest: "{{ path_zoo }}"
    state: link
  become: true

- name: copiando os arquivos de configuração
  template:
    src: "{{ item.orig }}"
    dest: "{{ item.dest }}"
    owner: "{{ user_zoo }}"
    backup: true
  with_items:
    - orig: zoo.cfg.j2
      dest: "{{ path_zoo }}/conf/zoo.cfg"
    - orig: jvm.properties.j2
      dest: "{{ path_zoo }}/conf/jvm.properties"
  become: true

- name: copiando o arquivo de service do zookeeper
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  notify:
    - inicia zookeeper
  become: true
